version: '3.9'
services:
  certbot:
    image: certbot/certbot
    networks:
      - internal
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "./data/certbot/conf:/etc/letsencrypt"
      - "./data/certbot/www:/var/www/certbot"

      - "./data/logs:/var/log/nginx:delegated"
    networks:
      - internal
    depends_on:
      - api
      - certbot
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env-db
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: bogdzn/theed
    container_name: theed
    ports:
      - "3000:3000"
    networks:
      - internal
    restart: unless-stopped

  api:
    image: arkulturtest/naboo:dev
    container_name: naboo
    env_file:
      - .env-api
    volumes:
      - ./configs/api:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:

volumes:
  pgdata:

