version: '3.9'
services:
  caddy:
    image: caddy:2
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env-db
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: bogdzn/theed:canon
    container_name: theed
    ports:
      - "3000:3000"
    networks:
      - internal
    restart: unless-stopped

  api:
    image: bogdzn/naboo:canon
    container_name: naboo
    env_file:
      - .env-api
    volumes:
      - ./configs/api:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:

volumes:
  pgdata:
  caddy_data:
  pgadmin-data:

