version: '3.9'
services:
  certbot:
    image: certbot/certbot
    networks:
      - internal
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "./data/certbot/conf:/etc/letsencrypt"
      - "./data/certbot/www:/var/www/certbot"
    networks:
      - internal
    depends_on:
      - api
      - client
      - certbot

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./server/api/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=naboo_dev
      - POSTGRES_PASSWORD=development
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    env_file:
      - .env-api
    build:
      context: ./naboo
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:development@db/naboo_dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal

  client:
    build:
      context: ./theed
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata:

